baseurl = "https://sustuseumr.github.io/vietnam/"

languageCode = "en-us"
title = "Vietnam"
theme = "hugo-lithium-theme"

disqusShortname = ""
publishDir = "docs"

[permalinks]
    post = "/:title/"
    page = "/:title/"
  
[[menu.main]]
    name = "About"
    url = "/about/"
#[[menu.main]]
#    name = "SLR Video"
#    url = "/slr/"
#[[menu.main]]
#   name = "Groundwater Video"
#    url = "/groundwater/"

[params]
    description = ""

    # path to the favicon, under "static"
    favicon = "favicon.ico"
	 
    [params.logo]
    url = "logo.png"
    width = 125
    height = 30
    alt = "Logo"

    [params.icon]
    url = "favicon.ico"

